import pandas as pd
import traceback
import os
from promptflow import tool


@tool
def execute_python_code(code: str):
    """
    Executes LLM-generated Python code against the Supply Chain dataset.

    :param code: The Python code string generated by the LLM.
    :return: A string representation of the 'result' variable or an error message.
    """

    file_path = "data/DataCoSupplyChainDataset.csv"

    # 1. Clean the code input (strip Markdown formatting)
    if not code:
        return "Error: No code provided by the LLM."

    if "```python" in code:
        code = code.split("```python")[1].split("```")[0].strip()
    elif "```" in code:
        code = code.split("```")[1].split("```")[0].strip()

    try:
        # 2. Load the dataset
        # ISO-8859-1 encoding is standard for this specific dataset
        df = pd.read_csv(file_path, encoding="ISO-8859-1")

        # 3. Standardize column names
        # Example: 'Delivery Status' -> 'Delivery_Status'
        # Example: 'Days for shipping (real)' -> 'Days_for_shipping_real'
        df.columns = [
            col.replace(" ", "_")
               .replace("(", "")
               .replace(")", "")
               .replace("/", "_")
               .replace("-", "_")
            for col in df.columns
        ]

        # 4. Define the execution environment
        # Pass 'df' and 'pd' into the local context
        # Initialize 'result' to capture output
        local_vars = {
            "df": df,
            "pd": pd,
            "result": None
        }

        # 5. Execute the code
        exec(code, {"__builtins__": __builtins__}, local_vars)

        # 6. Extract the 'result' variable
        execution_output = local_vars.get("result")

        if execution_output is None:
            return (
                "Success: Code executed, but no 'result' was assigned. "
                "Ensure your prompt tells the model to assign the answer "
                "to the 'result' variable."
            )

        # 7. Format the output for the next node (Synthesis)
        if isinstance(execution_output, (pd.DataFrame, pd.Series)):
            try:
                # Requires 'tabulate' package
                return execution_output.to_markdown()
            except ImportError:
                return execution_output.to_string()

        return str(execution_output)

    except Exception as e:
        # Return full traceback for debugging in Prompt Flow
        error_type = type(e).__name__
        return (
            f"Error during execution [{error_type}]: {str(e)}\n\n"
            f"Traceback:\n{traceback.format_exc()}"
        )